version: '2.1'

services:
  blob-router-service-db:
    build:
      context: ./docker/database
    image: hmcts/dm-store-db:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5434:5432
  azure-storage-emulator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --loose --skipApiVersionCheck
    environment:
      AZURITE_ACCOUNTS: crime:Y3JpbWVrZXkK;reformscanlocal:cmVmb3Jtc2NhbmtleQo=;bulkscanlocal:cmVmb3Jtc2NhbmtleQo=;pcqlocal:cmVmb3Jtc2NhbmtleQo=;jason:cmVmb3Jtc2NhbmtleQo=;mosh:cmVmb3Jtc2NhbmtleQo=;
    volumes:
      - ./bulk-scan-azure-blob-data:/opt/azurite/folder
    ports:
      - 10000:10000
  blob-router-service:
    build:
      context: ./
    links:
      - blob-router-service-db
    ports:
      - 8584:8584
    env_file:
      - .env
  init-storage:
    build:
      context: ./docker/storage
    links:
      - azure-storage-emulator-azurite
    depends_on:
      - azure-storage-emulator-azurite
