---
version: '3'

services:

  blob-router-db:
    build:
      context: ./docker/database
    image: hmcts/dm-store-db:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  azure-storage-emulator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --loose --skipApiVersionCheck
    environment:
      AZURITE_ACCOUNTS: crime:Y3JpbWVrZXkK;reformscanlocal:cmVmb3Jtc2NhbmtleQo=;bulkscanlocal:cmVmb3Jtc2NhbmtleQo=;pcqlocal:cmVmb3Jtc2NhbmtleQo=;
    volumes:
      - ./bulk-scan-azure-blob-data:/opt/azurite/folder
    ports:
      - 10000:10000

  init-storage:
    build:
      context: ./docker/storage
    links:
      - azure-storage-emulator-azurite
    depends_on:
      - azure-storage-emulator-azurite
