server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8

service:
  storage-config:
    - name: bulkscan
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
    - name: cmc
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
    - name: crime
      sas-validity: 300 #In seconds
      enabled: ${CRIME_ENABLED:false}
      target-storage-account: crime
    - name: divorce
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
    - name: finrem
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
    - name: probate
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
    - name: sscs
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

storage-blob-processing-delay-in-minutes: ${STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES}

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
  task:
    delete-dispatched-files:
      enabled: true
      cron: ${DELETE_DISPATCHED_FILES_CRON}
    scan:
      delay: ${TASK_SCAN_DELAY} # In milliseconds
