server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service

accesstoken:
  serviceConfig:
    - serviceName: bulkscan
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
