server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
  health:
    mail:
      enabled: false

spring:
  application:
    name: Blob Router Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: RouterHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

service:
  storage-config:
    - source-container: bulkscan
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: bulkscan
    - source-container: bulkscanauto
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: bulkscanauto
    - source-container: cmc
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: cmc
    - source-container: crime
      sas-validity: 300 #In seconds
      enabled: ${CRIME_ENABLED:false}
      target-storage-account: crime
      target-container: ${CRIME_DESTINATION_CONTAINER}
    - source-container: pcq
      sas-validity: 300 #In seconds
      enabled: ${PCQ_ENABLED:false}
      target-storage-account: pcq
      target-container: ${PCQ_DESTINATION_CONTAINER}
    - source-container: divorce
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: divorce
    - source-container: finrem
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: finrem
    - source-container: probate
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: probate
    - source-container: sscs
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: sscs
    - source-container: publiclaw
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: publiclaw

queue:
  notifications:
    access-key: ${NOTIFICATIONS_QUEUE_SEND_ACCESS_KEY}
    access-key-name: ${NOTIFICATIONS_QUEUE_ACCESS_KEY_SEND_NAME}
    namespace: ${NOTIFICATIONS_QUEUE_NAMESPACE}

reports:
  recipients: ${REPORTS_RECIPIENTS}

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

storage-blob-processing-delay-in-minutes: ${STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES}
public_key_der_file: ${STORAGE_BLOB_PUBLIC_KEY} # public key file in der format

sas-token-cache:
    refresh-before-expire-in-sec: 30

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
  task:
    delete-dispatched-files:
      enabled: true
      cron: ${DELETE_DISPATCHED_FILES_CRON}
    handle-rejected-files:
      enabled: true
      cron: ${HANDLE_REJECTED_FILES_CRON}
    reject-duplicates:
      enabled: true
      cron: ${REJECT_DUPLICATES_CRON}
    send-notifications:
      enabled: true
      cron: ${SEND_NOTIFICATIONS_CRON}
    delete-rejected-files:
      enabled: true
      ttl: PT72H # ISO-8601
      cron: 0 0 6 * * *
    check-new-envelopes:
      time-interval: PT60M # ISO-8601
      cron: ${CHECK_NEW_ENVELOPES_CRON}
      enabled: true
    scan:
      delay: ${TASK_SCAN_DELAY} # In milliseconds
    send-daily-report:
      cron: ${SEND_DAILY_REPORT_CRON}
      enabled: ${SEND_DAILY_REPORT_ENABLED}
    create-reconciliation-summary-report:
      cron: ${CREATE_RECONCILIATION_SUMMARY_REPORT_CRON}
      enabled: ${CREATE_RECONCILIATION_SUMMARY_REPORT_ENABLED}

proxy:
  enabled: ${PROXY_ENABLED:true}
  host-name: proxyout.reform.hmcts.net
  port: 8080

reconciliation:
  api-key: ${RECONCILIATION_API_KEY}

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME:reform_scan_blob_router}
