server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: db
  endpoints:
    web:
      base-path: /
  health:
    mail:
      enabled: false

spring:
  application:
    name: Blob Router Service
  config:
    import: "optional:configtree:/mnt/secrets/reform-scan/"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: RouterHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration,org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

# always use lower case container name
service:
  storage-config:
    - source-container: bulkscan
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: bulkscan
    - source-container: bulkscanauto
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: bulkscanauto
    - source-container: cmc
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: cmc
    - source-container: crime
      sas-validity: 300 #In seconds
      enabled: ${CRIME_ENABLED:false}
      target-storage-account: crime
      target-container: ${CRIME_DESTINATION_CONTAINER}
    - source-container: pcq
      sas-validity: 300 #In seconds
      enabled: ${PCQ_ENABLED:false}
      target-storage-account: pcq
      target-container: ${PCQ_DESTINATION_CONTAINER}
    - source-container: divorce
      sas-validity: 600 #In seconds
      target-storage-account: cft
      target-container: divorce
    - source-container: nfd
      sas-validity: 600 #In seconds
      target-storage-account: cft
      target-container: nfd
      enabled: ${NFD_ENABLED}
    - source-container: finrem
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: finrem
    - source-container: probate
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: probate
    - source-container: sscs
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: sscs
    - source-container: publiclaw
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: publiclaw
    - source-container: privatelaw
      sas-validity: 300 #In seconds
      target-storage-account: cft
      target-container: privatelaw
      enabled: ${PRIVATELAW_ENABLED}

queue:
  notifications:
    access-key: ${NOTIFICATIONS_QUEUE_SEND_ACCESS_KEY}
    access-key-name: ${NOTIFICATIONS_QUEUE_ACCESS_KEY_SEND_NAME}
    namespace: ${NOTIFICATIONS_QUEUE_NAMESPACE}
    queue-name: ${NOTIFICATIONS_QUEUE_NAME}

reports:
  recipients: ${REPORTS_RECIPIENTS}

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

storage-blob-lease-timeout-in-minutes: ${STORAGE_BLOB_LEASE_TIMEOUT_IN_MINUTES}
public_key_der_file: ${STORAGE_BLOB_PUBLIC_KEY} # public key file in der format

sas-token-cache:
    refresh-before-expire-in-sec: 30

upload-chunk-size-in-bytes:  6291456 #6 MB

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
  task:
    delete-dispatched-files:
      enabled: true
      cron: ${DELETE_DISPATCHED_FILES_CRON}
    handle-rejected-files:
      enabled: true
      cron: ${HANDLE_REJECTED_FILES_CRON}
    reject-duplicates:
      enabled: ${REJECT_DUPLICATES_ENABLED}
      cron: ${REJECT_DUPLICATES_CRON}
    send-notifications:
      enabled: true
      cron: ${SEND_NOTIFICATIONS_CRON}
    delete-rejected-files:
      enabled: true
      ttl: PT72H # ISO-8601
      cron: 0 0 6 * * *
    check-new-envelopes:
      time-interval: PT60M # ISO-8601
      cron: ${CHECK_NEW_ENVELOPES_CRON}
      enabled: true
    scan:
      delay: ${TASK_SCAN_DELAY} # In milliseconds
    send-daily-report:
      cron: ${SEND_DAILY_REPORT_CRON}
      enabled: ${SEND_DAILY_REPORT_ENABLED}
    create-reconciliation-summary-report:
      cron: ${CREATE_RECONCILIATION_SUMMARY_REPORT_CRON}
      enabled: ${CREATE_RECONCILIATION_SUMMARY_REPORT_ENABLED}
    create-reconciliation-detailed-report:
      cron: ${CREATE_RECONCILIATION_DETAILED_REPORT_CRON}
      enabled: ${CREATE_RECONCILIATION_DETAILED_REPORT_ENABLED}
    send-reconciliation-report-mail:
      cron: ${SEND_RECONCILIATION_REPORT_MAIL_CRON}
      enabled: ${SEND_RECONCILIATION_REPORT_MAIL_ENABLED}

reconciliation:
  api-key: ${RECONCILIATION_API_KEY}
  report:
      mail-from: ${SMTP_USERNAME}
      mail-recipients: ${RECONCILIATION_REPORT_RECIPIENTS}
      api-key: ${RECONCILIATION_REPORT_API_KEY}

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME:reform_scan_blob_router}

envelope-stale-timeout-hr: ${ENVELOPE_STALE_TIMEOUT_HR}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.blobrouter
  pathsToMatch:
    - /reconciliation-report/*
    - /token/*
  swagger-ui:
    use-root-path: true

actions:
  api-key: ${ACTIONS_API_KEY}

jms:
  # Set to disable configuration in envs besides local/dev
  enabled: ${JMS_ENABLED:false}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:XXXXX}
  offline-mode: ${LAUNCH_DARKLY_OFFLINE_MODE:false}
