server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: RouterHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

service:
  storage-config:
    - source-container: bulkscan
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: bulkscan
    - source-container: cmc
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: cmc
    - source-container: crime
      sas-validity: 300 #In seconds
      enabled: ${CRIME_ENABLED:false}
      target-storage-account: crime
      target-container: ${CRIME_DESTINATION_CONTAINER}
    - source-container: divorce
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: divorce
    - source-container: finrem
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: finrem
    - source-container: probate
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: probate
    - source-container: sscs
      sas-validity: 300 #In seconds
      target-storage-account: bulkscan
      target-container: sscs

reports:
  recipients: ${REPORTS_RECIPIENTS}

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

storage-blob-processing-delay-in-minutes: ${STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES}
public_key_der_file: ${STORAGE_BLOB_PUBLIC_KEY} # public key file in der format

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
  task:
    delete-dispatched-files:
      enabled: true
      cron: ${DELETE_DISPATCHED_FILES_CRON}
    handle-rejected-files:
      enabled: true
      cron: ${HANDLE_REJECTED_FILES_CRON}
    reject-duplicates:
      enabled: true
      cron: ${REJECT_DUPLICATES_CRON}
    delete-rejected-files:
      enabled: true
      ttl: PT72H # ISO-8601
      cron: 0 0 6 * * *
    check-new-envelopes:
      cron: ${CHECK_NEW_ENVELOPES_CRON}
      enabled: true
    scan:
      delay: ${TASK_SCAN_DELAY} # In milliseconds
    send-daily-report:
      cron: ${SEND_DAILY_REPORT_CRON}
      enabled: false

proxy:
  enabled: ${PROXY_ENABLED:true}
  host-name: proxyout.reform.hmcts.net
  port: 8080
