server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8

service:
  storage-config:
    - name: bulkscan
      sas-validity: 300 #In seconds
    - name: cmc
      sas-validity: 300 #In seconds
    - name: crime
      sas-validity: 300 #In seconds
      enabled: ${CRIME_ENABLED:false}
    - name: divorce
      sas-validity: 300 #In seconds
    - name: finrem
      sas-validity: 300 #In seconds
    - name: probate
      sas-validity: 300 #In seconds
    - name: sscs
      sas-validity: 300 #In seconds

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
