server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service

service:
  storage-config:
    - name: bulkscan
      sas-validity: 300 #In seconds
