server:
  port: 8584

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Blob Router Service

storage:
  account-name: ${STORAGE_ACCOUNT_NAME:reformscanaat}
  account-key: ${STORAGE_ACCOUNT_KEY:dGVzdA==} #Base 64 encoded
  account-secondary-key: ${STORAGE_ACCOUNT_SECONDARY_KEY:dGVzdA==} #Base 64 encoded

service:
  storage-config:
    - name: bulkscan
      sas-validity: 300 #In seconds
