apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Blob Router Service
name: reform-scan-blob-router
home: https://github.com/hmcts/blob-router-service
version: 0.0.24
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
