dependencies:
  - name: java
    version: ~2.13.0
    repository: '@hmctspublic'
  - name: blobstorage
    alias: reformblobstorage
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: reformblobstorage.enabled
  - name: blobstorage
    alias: cftblobstorage
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: cftblobstorage.enabled
  - name: blobstorage
    alias: crimeblobstorage
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: crimeblobstorage.enabled
  - name: bulk-scan-processor
    alias: bulkscanprocessor
    version: ~0.2.16
    repository: '@hmctspublic'
    condition: bulkscanprocessor.enabled
