java:
  secrets:
    STORAGE_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_ACCOUNT_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_ACCOUNT_SECONDARY_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_BULKSCAN_ACCOUNT_NAME:
      secretRef: cft-storage-secret-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_BULKSCAN_ACCOUNT_KEY:
      secretRef: cft-storage-secret-{{ .Release.Name }}
      key: accessKey
  environment:
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:

reformblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected
