java:
  secrets:
    STORAGE_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_ACCOUNT_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_ACCOUNT_SECONDARY_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_BULKSCAN_ACCOUNT_NAME:
      secretRef: storage-secret-cft-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_BULKSCAN_ACCOUNT_KEY:
      secretRef: storage-secret-cft-{{ .Release.Name }}
      key: accessKey
    STORAGE_CRIME_ACCOUNT_NAME:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_CRIME_ACCOUNT_KEY:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: accessKey
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
  environment:
    DB_HOST: "{{ .Release.Name }}-postgresql"
    DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    DB_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DB_CONN_OPTIONS: ""

    DELETE_DISPATCHED_FILES_CRON: "0/10 * * * * *"
    TASK_SCAN_DELAY: "1000" # in millis

    FLYWAY_SKIP_MIGRATIONS: false
    FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase}}"
    FLYWAY_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    FLYWAY_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES: 0

    STORAGE_BULKSCAN_URL: "https://$(STORAGE_BULKSCAN_ACCOUNT_NAME).blob.core.windows.net"
    STORAGE_CRIME_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=$(STORAGE_CRIME_ACCOUNT_NAME);AccountKey=$(STORAGE_CRIME_ACCOUNT_KEY);EndpointSuffix=core.windows.net"
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:

  postgresql:
    enabled: true
    postgresqlUsername: db_user
    postgresqlPassword: db_pass
    postgresqlDatabase: db

reformblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected
      - crime
      - crime-rejected

cftblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: cft-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected

crimeblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: crime-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - crime
