java:
  secrets:
    STORAGE_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_ACCOUNT_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_ACCOUNT_SECONDARY_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessSecondaryKey
    STORAGE_BULKSCAN_ACCOUNT_NAME:
      secretRef: storage-secret-cft-{{ .Release.Name }}
      key: cftStorageAccountName
    STORAGE_BULKSCAN_ACCOUNT_KEY:
      secretRef: storage-secret-cft-{{ .Release.Name }}
      key: cftAccessKey
    STORAGE_CRIME_ACCOUNT_NAME:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: crimeStorageAccountName
    STORAGE_CRIME_ACCOUNT_KEY:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: crimeAccessKey
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
  environment:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:

reformblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected
      - crime
      - crime-rejected

cftblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: cft-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected

crimeblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: crime-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - crime
