java:
  environment:
    CRIME_ENABLED: "true"
    STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES: 0
    DELETE_DISPATCHED_FILES_CRON: "0/10 * * * * *"
    SEND_NOTIFICATIONS_CRON: "0/10 * * * * *"
    SEND_DAILY_REPORT_ENABLED: "false"
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devApplicationInsightsInstrumentKey: "fb929548-3309-4933-bd6e-f7932b4e0309"
