java:
  applicationPort: 8584
  ingressHost: reform-scan-blob-router-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: reform-scan
  readinessPath: '/health/readiness'
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - app-insights-instrumentation-key
        - reports-email-username
        - reports-email-password
        - reports-recipients
        - storage-account-name
        - storage-account-primary-key
        - storage-account-secondary-key
        - crime-storage-connection-string
        - blob-router-POSTGRES-PASS
        - blob-router-POSTGRES-USER
        - blob-router-POSTGRES-HOST
        - blob-router-POSTGRES-PORT
        - blob-router-POSTGRES-DATABASE
        - notification-queue-send-shared-access-key
        - reconciliation-api-key
        - s2s-secret-blob-router

  environment:
    DB_CONN_OPTIONS: ?sslmode=require
    FLYWAY_SKIP_MIGRATIONS: true

    S2S_NAME: "reform_scan_blob_router"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"

    DELETE_DISPATCHED_FILES_CRON: "0 0/10 * * * *"
    HANDLE_REJECTED_FILES_CRON: "0/30 * * * * *"
    REJECT_DUPLICATES_CRON: "0/30 * * * * *"
    CHECK_NEW_ENVELOPES_CRON: "0 0 * * * *"
    TASK_SCAN_DELAY: "4000" # in millis
    SEND_DAILY_REPORT_CRON: "0 0 6 ? * *"
    SEND_NOTIFICATIONS_CRON: "0 0/10 * * * *"

    CREATE_RECONCILIATION_SUMMARY_REPORT_CRON: "0 */30 1-11 * * *"
    CREATE_RECONCILIATION_SUMMARY_REPORT_ENABLED: "false"

    STORAGE_URL: https://reformscan.{{ .Values.global.environment }}.platform.hmcts.net
    STORAGE_BULKSCAN_URL: https://bulkscan.{{ .Values.global.environment }}.platform.hmcts.net
    STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES: 30
    STORAGE_BLOB_PUBLIC_KEY: "nonprod_public_key.der"
    CRIME_DESTINATION_CONTAINER: bs-sit-scans-received
    PCQ_DESTINATION_CONTAINER: pcq

    NOTIFICATIONS_QUEUE_ACCESS_KEY_SEND_NAME: "SendSharedAccessKey"
    NOTIFICATIONS_QUEUE_NAMESPACE: reform-scan-servicebus-{{ .Values.global.environment }}

    BULK_SCAN_PROCESSOR_URL: http://bulk-scan-processor-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PCQ_BACKEND_API_URL: "http://pcq-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"

    SMTP_HOST: "false"
    SEND_DAILY_REPORT_ENABLED: "false"
  image: 'hmctspublic.azurecr.io/reform-scan/blob-router:latest'
reformblobstorage:
  enabled: false
cftblobstorage:
  enabled: false
crimeblobstorage:
  enabled: false
pcqblobstorage:
  enabled: false

servicebus:
  enabled: false
