java:
  applicationPort: 8584
  ingressHost: reform-scan-blob-router-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: reform-scan
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - app-insights-instrumentation-key
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
        - storage-account-name
        - storage-account-primary-key
        - storage-account-secondary-key
        - bulkscan-storage-connection-string
        - crime-storage-connection-string
        - flyway-password
        - blob-router-POSTGRES-PASS
  environment:
    DB_HOST: reform-scan-blob-router-{{ .Values.global.environment }}.postgres.database.azure.com
    DB_PORT: '5432'
    DB_NAME: blob_router
    DB_USER: blob_router@reform-scan-blob-router-{{ .Values.global.environment }}
    DB_CONN_OPTIONS: ?sslmode=require

    FLYWAY_URL: jdbc:postgresql://blob_router-{{ .Values.global.environment }}.postgres.database.azure.com:5432/blob_router?sslmode=require
    FLYWAY_USER: blob_router@blob_router-{{ .Values.global.environment }}
    FLYWAY_SKIP_MIGRATIONS: true
    STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES: 30
  image: 'hmctspublic.azurecr.io/reform-scan/blob-router:latest'
reformblobstorage:
  enabled: false
cftblobstorage:
  enabled: false
crimeblobstorage:
  enabled: false
