java:
  applicationPort: 8584
  ingressHost: reform-scan-blob-router-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: reform-scan
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - app-insights-instrumentation-key
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
        - storage-account-name
        - storage-account-primary-key
        - storage-account-secondary-key
        - bulkscan-storage-account-name
        - bulkscan-storage-account-primary-key
        - crime-storage-account-name
        - crime-storage-account-primary-key
        - flyway-password
  environment:
    FLYWAY_URL: jdbc:postgresql://blob_router-{{ .Values.global.environment }}.postgres.database.azure.com:5432/bulk_scan?sslmode=require
    FLYWAY_USER: blob_router@blob_router-{{ .Values.global.environment }}
    FLYWAY_SKIP_MIGRATIONS: true
  image: 'hmctspublic.azurecr.io/reform-scan/blob-router:latest'
reformblobstorage:
  enabled: false
cftblobstorage:
  enabled: false
crimeblobstorage:
  enabled: false
